
package wstest2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "welcome", targetNamespace = "http://wstest2/", wsdlLocation = "http://10.134.119.237:9090/SoapUITestingProject/MathAndStrings?wsdl")
public class Welcome
    extends Service
{

    private final static URL WELCOME_WSDL_LOCATION;
    private final static WebServiceException WELCOME_EXCEPTION;
    private final static QName WELCOME_QNAME = new QName("http://wstest2/", "welcome");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.134.119.237:9090/SoapUITestingProject/MathAndStrings?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WELCOME_WSDL_LOCATION = url;
        WELCOME_EXCEPTION = e;
    }

    public Welcome() {
        super(__getWsdlLocation(), WELCOME_QNAME);
    }

    public Welcome(WebServiceFeature... features) {
        super(__getWsdlLocation(), WELCOME_QNAME, features);
    }

    public Welcome(URL wsdlLocation) {
        super(wsdlLocation, WELCOME_QNAME);
    }

    public Welcome(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WELCOME_QNAME, features);
    }

    public Welcome(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Welcome(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StringMathWebService
     */
    @WebEndpoint(name = "StringMathWebServicePort")
    public StringMathWebService getStringMathWebServicePort() {
        return super.getPort(new QName("http://wstest2/", "StringMathWebServicePort"), StringMathWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StringMathWebService
     */
    @WebEndpoint(name = "StringMathWebServicePort")
    public StringMathWebService getStringMathWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wstest2/", "StringMathWebServicePort"), StringMathWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WELCOME_EXCEPTION!= null) {
            throw WELCOME_EXCEPTION;
        }
        return WELCOME_WSDL_LOCATION;
    }

}
