
package wstest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MathService", targetNamespace = "http://wstest/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MathService {


    /**
     * 
     * @param number1
     * @param number2
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "sum", targetNamespace = "")
    @RequestWrapper(localName = "addNumbers", targetNamespace = "http://wstest/", className = "wstest.AddNumbers")
    @ResponseWrapper(localName = "addNumbersResponse", targetNamespace = "http://wstest/", className = "wstest.AddNumbersResponse")
    @Action(input = "http://wstest/MathService/addNumbersRequest", output = "http://wstest/MathService/addNumbersResponse")
    public int addNumbers(
        @WebParam(name = "number1", targetNamespace = "")
        int number1,
        @WebParam(name = "number2", targetNamespace = "")
        int number2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtractNumbers", targetNamespace = "http://wstest/", className = "wstest.SubtractNumbers")
    @ResponseWrapper(localName = "subtractNumbersResponse", targetNamespace = "http://wstest/", className = "wstest.SubtractNumbersResponse")
    @Action(input = "http://wstest/MathService/subtractNumbersRequest", output = "http://wstest/MathService/subtractNumbersResponse")
    public int subtractNumbers(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
