
package source;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentData", targetNamespace = "http://source/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentData {


    /**
     * 
     * @param rollNo
     * @return
     *     returns source.Student
     */
    @WebMethod(operationName = "GetStudent")
    @WebResult(name = "Stu", targetNamespace = "")
    @RequestWrapper(localName = "GetStudent", targetNamespace = "http://source/", className = "source.GetStudent")
    @ResponseWrapper(localName = "GetStudentResponse", targetNamespace = "http://source/", className = "source.GetStudentResponse")
    @Action(input = "http://source/StudentData/GetStudentRequest", output = "http://source/StudentData/GetStudentResponse")
    public Student getStudent(
        @WebParam(name = "RollNo", targetNamespace = "")
        int rollNo);

}
